### ISSUE TITLE
Fix Linux

### ISSUE THREAD

**Issue by ezpzbrah** [mcjp78/AltLoaderDownloads#1]
When everyone was forced to update to version 0.3.1 of Alt Loader, Linux couldn't use 0.3.1 because only the oldest version of Alt Loader worked. When will a Linux version be released?!

**Comment by GramDev1** [comment]
Working on this now.

Sent from my Apple Watch

On May 16, 2016, at 7:26 AM, ezpzbrah <notifications@github.com<mailto:notifications@github.com>> wrote:

When everyone was forced to update to version 0.3.1 of Alt Loader, Linux couldn't use it. When will a Linux version be released!

**Comment by ezpzbrah** [comment]
Still not fixed :(

**Comment by GramDev1** [comment]
Yes I know, will be patched in a few hours

**Comment by ezpzbrah** [comment]
Yet, in 15 hours it's not patched :( I know I'm impatient.

**Comment by GramDev1** [comment]
The error seems to be something whilst detecting the os. I just got s Linux box to test the software on

Sent from my iPhone

On May 17, 2016, at 7:35 AM, ezpzbrah <notifications@github.com<mailto:notifications@github.com>> wrote:

Yet, in 15 hours it's not patched :( I know I'm impatient.

##

**Comment by ezpzbrah** [comment]
So will it be done today? (PCT timezone)

**Comment by GramDev1** [comment]
Just finished it, I think. Test it?

**Comment by GramDev1** [comment]
Patch confirmed working, closing this issue.
