### ISSUE TITLE
Mac still doesn't work

### ISSUE THREAD

**Issue by AlhassanKH** [mcjp78/AltLoaderDownloads#10]
I get this
execution error: Exception in thread "main" java.lang.ArrayIndexOutOfBoundsExceptat net.altdispenser.altloader.AltLoader.main(AltLoader.java:72) (1)
logout

I have Java

**Comment by ezpzbrah** [comment]
I'm not sure if Mac is working for anyone rn. The Dev's will work on a fix soon if they aren't already.

**Comment by JorgenVatle** [comment]
Within the next couple of weeks, we'll have a new Alt Loader system which will work with all operating systems that can run Java 8. Apologies for the inconvenience.
