### ISSUE TITLE
Mac doesn't work.

### ISSUE THREAD

**Issue by AlhassanKH** [mcjp78/AltLoaderDownloads#9]
I have the latest Java 8 update 101, installed the new Alt loader and ran the .command, then it told me it needs Java runtime which I have (Java 8 update 101).
Any solutions?
I restarted/reinstalled

**Comment by Tomygames** [comment]
Yeah :(, i hope worthy fixes it x)

**Comment by ezpzbrah** [comment]
Mac is being fixed. Just because a Dev doesn't respond doesn't mean they don't care.
